package ai.util;

import java.util.Random; 

/**
 * @author david kawrykow and gen kazama
 * 
 * Is used by AI to generate random numbers between 0 and 100. Also allows
 * test classes to get the first n expected numbers from the generator
 *
 */
public class AINumberGenerator {

	private final int SEED;
	private final int MAX = 101; 
	
	Random NumberGenerator; 
	
	/**
	 * Creates a new AINumberGenerator
	 * @param Seed Will produce the same sequence of numbers of every time. 
	 */
	public AINumberGenerator(int Seed)
	{
		SEED = Seed; 
		NumberGenerator = new Random(SEED); 
	}
	
	/**
	 * @return The upper bound on the uniform interval 
	 */
	public int getMaximumFeasible()
	{
		return MAX; 
	}
	
	/**
	 * @return The next AIInteger
	 */
	public int getNextInteger()
	{
		return NumberGenerator.nextInt(MAX); 
	}
	
	/**
	 * Returns The first n integers to be generated by this class under the current
	 * seed. Note that it does not return the next n integers, but the first n. 
	 * @param n
	 * @pre n > 0
	 */
	public int[] getIntegerSequence(int n)
	{
		assert (n > 0);
		
		int ToReturn[] = new int[n]; 
		Random x = new Random(SEED); 
		
		for(int i = 0; i < n; i++)
			ToReturn[i] = x.nextInt(MAX);
		
		return ToReturn; 
	}
}
